# -*- coding: utf-8 -*-
"""Binance_scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CFIJAdthlrnAyO_EmOsY7P7_6HsSlnH_
"""

import requests
import json

# Endpoint URL
url = "https://www.binance.com/bapi/futures/v1/public/future/copy-trade/lead-portfolio/trade-history"

# List to store the combined 'list' items from each page's data
combined_list_data = []
portfolio_id = ''
start_page =
end_page =

# Function to make POST request with a given page number
def make_request(page_number):
    # Payload to be sent in POST request
    payload = {
        "pageNumber": page_number,
        "pageSize": 10,
        "portfolioId": portfolio_id
    }

    # Make the POST request
    response = requests.post(url, json=payload)

    # Check if the request was successful
    if response.status_code == 200:
        print(f"Page {page_number}: Success")
        # Extract list items and append them to combined_list_data
        response_data = response.json()
        combined_list_data.extend(response_data['data']['list'])
    else:
        print(f"Page {page_number}: Error - {response.status_code}")

for page_number in range(start_page, end_page+1):
    make_request(page_number)

# Save the combined list data to a file
with open('combined_list_data.json', 'w') as file:
    json.dump(combined_list_data, file)

print("Data saved to combined_list_data.json")

import json
import csv

# Load JSON data from a file
with open('/content/fulldata.json', 'r') as json_file:
    json_data = json.load(json_file)

# Define the CSV file name
csv_file_name = 'combined_list_data.csv'

# Convert JSON data to CSV
with open(csv_file_name, 'w', newline='') as csv_file:
    writer = csv.DictWriter(csv_file, fieldnames=json_data[0].keys())
    writer.writeheader()
    for data in json_data:
        writer.writerow(data)

print(f"Data successfully written to {csv_file_name}")